
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ynbwhrvvpcgoowwtnpbp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InluYndocnZ2cGNnb293d3RucGJwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDA0NjQ0MzYsImV4cCI6MjA1NjA0MDQzNn0.vVEfUVz2EZjoK1HCbbjd8ZJYhp6cm-cE4VVZES9lFco";

// Configure client with options to optimize performance
const supabaseOptions = {
  auth: {
    autoRefreshToken: true,
    persistSession: true
  },
  realtime: {
    timeout: 30000, // Increase timeout to 30s
    params: {
      eventsPerSecond: 10
    }
  }
};

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, supabaseOptions);

// Optional: Add convenience method to directly open the dashboard
export const openSupabaseDashboard = (path = "") => {
  const projectId = "ynbwhrvvpcgoowwtnpbp";
  window.open(`https://supabase.com/dashboard/project/${projectId}${path}`, "_blank");
};
