// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ynbwhrvvpcgoowwtnpbp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InluYndocnZ2cGNnb293d3RucGJwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDA0NjQ0MzYsImV4cCI6MjA1NjA0MDQzNn0.vVEfUVz2EZjoK1HCbbjd8ZJYhp6cm-cE4VVZES9lFco";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);